// <auto-generated />
using System;
using JorgeMoncayo_Examen1P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JorgeMoncayo_Examen1P.Migrations
{
    [DbContext(typeof(JorgeMoncayo_Examen1PContext))]
    partial class JorgeMoncayo_Examen1PContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JorgeMoncayo_Examen1P.Models.JorgeMoncayo_tabla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NombreJuego")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PrecioDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ps4")
                        .HasColumnType("bit");

                    b.Property<bool>("Ps5")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("JorgeMoncayo_tabla");
                });
#pragma warning restore 612, 618
        }
    }
}
